language: objective-c
osx_image: xcode11.2
node_js:
  - "12"

before_script:
  - npm install -g swiftx
  - export SWIFTX_CONFIG_PATH=builds/swift/config

script:
  - swift build

after_success:
  - swiftx update-build-config
  - swiftx update-dependency-graph
  - swiftx trigger-downstream-builds

after_failure:
  - swiftx trigger-downstream-builds --force
