language: objective-c
osx_image: xcode8.2
node_js:
  - "6"

before_script:
  - npm install -g swiftx

script:
  - swift build
  - ls -l

after_success:
  - ls -l
  - swiftx update-build-config --owner randymarsh77 --configPath builds/swift/config
  - swiftx update-dependency-graph --owner randymarsh77 --configPath builds/swift/config
  - swiftx trigger-downstream-builds --owner randymarsh77 --configPath builds/swift/config
